FROM ghcr.io/m1k1o/neko/firefox:latest
# 临时切换 root 修复安全漏洞
USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3.9=3.9.2-1+deb11u4 \
        libpython3.9-stdlib=3.9.2-1+deb11u4 \
        libpython3.9-minimal=3.9.2-1+deb11u4 \
        python3.9-minimal=3.9.2-1+deb11u4 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
# 恢复非 root 用户
USER 10014
